---
driver:
  name: default
  options:
    managed: true

platforms:
  - name: rocky8
    image: ${HOME}/qemu-images/Rocky-8-GenericCloud.latest.x86_64.raw
    memory: 4096
    cpus: 2
    disk_size: 12G
    ssh_port: 2236
    ssh_user: rocky
    ssh_key: ~/.ssh/id_rsa
    disk_interface: virtio

provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      rocky8:
        ansible_python_interpreter: /usr/bin/python3.9
  playbooks:
    create: ../shared/create.yml
    prepare: ../shared/prepare.yml
    destroy: ../shared/destroy.yml
    converge: ../shared/converge.yml

verifier:
  name: ansible
