---
driver:
  name: default
  options:
    managed: true

platforms:
  - name: debian12-arm64-pxb84-upgrade
    arch: arm64
    image: ${HOME}/qemu-images/debian-12-genericcloud-arm64.raw
    memory: 2048
    cpus: 2
    disk_size: 20G
    ssh_port: 2254
    ssh_user: debian
    ssh_key: ~/.ssh/id_rsa

provisioner:
  name: ansible
  log: true
  playbooks:
    create: ../../shared/create.yml
    prepare: ../../shared/prepare.yml
    destroy: ../../shared/destroy.yml
    converge: ../../shared/converge-pxb84-upgrade.yml

verifier:
  name: ansible
