---
driver:
  name: default
  options:
    managed: true

platforms:
  - name: rocky9
    image: ${HOME}/qemu-images/Rocky-9-GenericCloud.latest.x86_64.raw
    memory: 4096
    cpus: 2
    disk_size: 12G
    ssh_port: 2237
    ssh_user: rocky
    ssh_key: ~/.ssh/id_rsa
    disk_interface: virtio

provisioner:
  name: ansible
  log: true
  playbooks:
    create: ../shared/create.yml
    destroy: ../shared/destroy.yml
    converge: ../shared/converge.yml

verifier:
  name: ansible
