---
driver:
  name: default
  options:
    managed: true

platforms:
  - name: ubuntu22-arm64-upgrade
    arch: arm64
    image: ${HOME}/qemu-images/jammy-server-cloudimg-arm64.raw
    memory: 4096
    cpus: 2
    disk_size: 12G
    ssh_port: 2260
    ssh_user: ubuntu
    ssh_key: ~/.ssh/id_rsa
    disk_interface: virtio

provisioner:
  name: ansible
  log: true
  playbooks:
    create: ../shared/create.yml
    prepare: ../shared/prepare.yml
    destroy: ../shared/destroy.yml
    converge: ../shared/converge.yml

verifier:
  name: ansible
