---
driver:
  name: default
  options:
    managed: true

platforms:
  - name: ubuntu24-arm64
    arch: arm64
    image: ${HOME}/qemu-images/noble-server-cloudimg-arm64.raw
    memory: 1536
    cpus: 2
    disk_size: 12G
    ssh_port: 2245
    ssh_user: ubuntu
    ssh_key: ~/.ssh/id_rsa
    disk_interface: virtio

provisioner:
  name: ansible
  log: true
  playbooks:
    create: ../shared/create.yml
    destroy: ../shared/destroy.yml
    converge: ../shared/converge.yml

verifier:
  name: ansible
